# observe_window: 12
# predict_window: [3]
# fold: 1
# no_imputation: true
# batch_size: 100
epoch: 60
hidden_size: 100
l2: 1.0e-04
lr: 0.0001
# lr_dc: 0.5
lr_dc_step: 20
# num_layers: 2
# use_gat: false
# use_san: false
remove_normal_nodes: false
# add_trends: false
# add_layer4: false
nrs: 'nds'  # negative_random_samples